# Generated by Django 2.2.7 on 2019-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191123_1327'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='github_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('github_id', 'user')},
        ),
    ]
