# Generated by Django 2.2.7 on 2019-11-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191123_1327'),
        ('repository', '0002_auto_20191123_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='user',
            new_name='github_user',
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('github_id', 'github_user')},
        ),
    ]
