# Generated by Django 2.2.7 on 2019-11-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20191123_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_set', to='user.GithubUser')),
            ],
            options={
                'db_table': 'issue',
                'managed': True,
            },
        ),
    ]
