# Generated by Django 2.2.7 on 2019-11-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20191123_2025'),
        ('issue', '0002_issue_connector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='connector',
        ),
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_set', to='repository.Repository'),
        ),
    ]
