# Generated by Django 2.2.7 on 2019-11-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20191123_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='user',
            new_name='author',
        ),
    ]
