# Generated by Django 2.2.7 on 2019-11-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191123_1327'),
        ('issue', '0004_auto_20191123_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(max_length=45)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.GithubUser')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.Issue')),
            ],
            options={
                'db_table': 'issue_comment',
                'managed': True,
            },
        ),
    ]
