# Generated by Django 2.2.7 on 2019-11-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='type',
            field=models.CharField(choices=[('organization', 'organization'), ('user', 'user'), ('enterprise', 'enterprise')], max_length=20),
        ),
        migrations.DeleteModel(
            name='GithubType',
        ),
    ]
