# Generated by Django 2.2.7 on 2019-11-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_connector_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connector',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='connector',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
