# Generated by Django 2.2.7 on 2019-11-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0005_comment'),
        ('user', '0005_auto_20191123_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.DateTimeField()),
                ('is_reminded', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.GithubUser')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.Issue')),
            ],
            options={
                'db_table': 'remind',
                'managed': True,
                'unique_together': {('issue', 'github_user')},
            },
        ),
    ]
