# Generated by Django 2.2.7 on 2019-11-29 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_comment'),
        ('user', '0005_auto_20191123_1327'),
        ('bot_reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remind',
            old_name='github_user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='remind',
            unique_together={('issue', 'author')},
        ),
    ]
